-- 1. Disable Row Level Security (RLS) safely
-- Using IF EXISTS so it doesn't throw errors if some tables haven't been created yet.
ALTER TABLE IF EXISTS profiles DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS companies DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS contacts DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS pipeline_stages DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS referral_codes DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS leads DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS stage_history DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS deals DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS activities DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS tasks DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS task_reminders DISABLE ROW LEVEL SECURITY;

-- 2. Add the missing venture column to the tasks table
ALTER TABLE IF EXISTS tasks ADD COLUMN IF NOT EXISTS venture TEXT NOT NULL DEFAULT 'core';

-- 3. Add the missing venture column to the leads table (required for VentureBadges)
ALTER TABLE IF EXISTS leads ADD COLUMN IF NOT EXISTS venture TEXT NOT NULL DEFAULT 'skill_tank';
